name: Codecov
on: push
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0, 3.10.3, 3.10.4]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run test database
        run: docker run -d yzh44yzh/wg_forge_backend_env:1.1
      - name: Run tests and collect coverage
        env:
          POSTGRES_SERVER: 0.0.0.0:5432
          POSTGRES_DB: wg_forge_db
          POSTGRES_USER: wg_forge
          POSTGRES_PASSWORD: 42a
        run: |
          make test
          make coverage-report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
